# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
